{
 "title": "SBMS0 RV (300 Ah @ 24V LifeP04 / 1890w PV )",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Battery Energy  (In/Out)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "Battery Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "bat cur" ], "type": "alias" }
      ],
      [
       { "params": [ "Battery Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "bat volt" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Battery %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "State of Charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Loads Total Watts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "PV Total Current" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "pv current" ], "type": "alias" }
      ],
      [
       { "params": [ "Battery Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "bat volt" ], "type": "alias" }
      ],
      [
       { "params": [ "Battery Current" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Bat Current" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Solar PV Watts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "PV Total Current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PV Total Current" ], "type": "alias" }
      ],
      [
       { "params": [ "Battery Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Battery Voltage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Battery % over time",
   "type": "graph",
   "description": "Battery State of Charge",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "SOC %" }
   ],
   "targets": [
    {
     "alias": "SOC%",
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "State of Charge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Internal Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Internal Temp",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "Internal Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Cell 1",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 1\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Cell 1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell 2",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 2\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Cell 2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell 3",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 3\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Cell 3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell 4",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 4\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Cell 4" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell 5",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 5\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Cell 5" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell 6",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 6\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Cell 6" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell 7",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 7\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Cell 7" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell 8",
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Cell 8\" FROM \"autogen\".\"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Cell 8" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Cell Delta",
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "Cell Delta" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    },
    {
     "alias": "Battery Bank",
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "Battery Voltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Monitor Flags",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "SBMS_Metrics",
     "query": "SELECT last(\"Monitor Flags\") FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a') AND $timeFilter",
     "select": [
      [
       { "params": [ "Monitor Flags" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "title": "Last Data Point",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 14 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "SBMS_Metrics",
     "query": "SELECT \"Battery Voltage\" FROM \"SBMS_Metrics\" WHERE (\"Name\" = 'SBMS0a')",
     "select": [
      [
       { "params": [ "Battery Voltage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 1, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SBMS_Metrics",
     "select": [
      [
       { "params": [ "State of Charge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Name", "operator": "=", "value": "SBMS0a" }
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 1, "w": 5, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 1, "w": 5, "x": 13, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 1, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 1, "w": 6, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 1, "w": 5, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 1, "x": 13, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 1, "x": 10, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}